iris
iris$Sepal.Length
mean(iris$Sepal.Length)
x=mean(iris$Sepal.Length)
x
iris$Sepal.Width
mean(iris$Sepal.Width)
y=mean(iris$Sepal.Width)
y
iris$Petal.Length
mean(iris$Petal.Length)
z=mean(iris$Petal.Length)
z
iris$Petal.Width
mean(iris$Petal.Width)
h=mean(iris$Petal.Width)
h
list(x,y,x,h)
length(list(x,y,x,h))